### ISSUE TITLE
hr utilization report: how to include leaves

### ISSUE THREAD

**Issue by miscs** [acsone/acsone-addons#114]
Hi all,

I just downloaded and installed your hr_utilization addon. Looks great, thanks for sharing!

The only problem I have is that I can´t figure out how to include leaves (sick, holidays,...) in the report. 
In the Tab HR: Utilization->Columns I can only add projects.

This results in wrong TOTAL percentages, because leaves are not taken into account. 

Any hints would be highly appreciated.
Thanks
Steve

**Comment by sbidoul** [comment]
Thanks for your interest. We ask users to fill timesheets for sick leave and holidays too on dedicated analytic accounts. 

From a process perspective it's also better: we also have a way to verify that employee do not forget to enter some timesheets.

**Comment by miscs** [comment]
Thanks for your fast reply!

So you ask your users to do a leave request (sick, holiday, ...) and to fill timesheet for these events? Or don´t you use the "Leave-Request"-function at all?

Thanks!

**Comment by miscs** [comment]
Last question (sorry for the trouble - and bit out of topic): is it possible to configure the report so that it is shown in HTML instead of PDF? Thanks!

**Comment by sbidoul** [comment]
@miscs Yes we ask users to do both timesheets and leave requests. Best way to catch errors (forgotton leave requests, etc).

The report is a webkit report so PDF only. You are welcome to propose a PR to replace it with qweb.

**Comment by miscs** [comment]
Thanks a lot for your answers and time!
