### ISSUE TITLE
Move to OCA some interesting modules

### ISSUE THREAD

**Issue by rafaelbn** [acsone/acsone-addons#123]
Hello @sbidoul , @JonathanNEMRY , @lmignon ,

I would like to ask, don't you think this modules could be very interesting for general purpose in OCA? (Social and Events)
- https://github.com/acsone/acsone-addons/blob/8.0/distribution_list
  # Distribution List
  
  This module provide features to allow the user to
  - create distribution lists composed with dynamic filters (odoo domain)
  - manage those distribution lists by adding or deleting lines
    _
- https://github.com/acsone/acsone-addons/tree/8.0/mass_mailing_distribution_list
  
  This module make a link between distribution list and mass mailing.
  
  It allows: \* to declare a distribution list as a newsletter to also define static lists of partners (opt In/Out) \* to unsubscribe partner (i.e. add it to the opt Out list) through the unsubscribe link added to the mailing \* to receive an external mail and forward it to all recipients filtered by the distribution list
- https://github.com/acsone/acsone-addons/tree/8.0/event_mass_mailing
  # Event Mass Mailing
  
  This module associates mass mailing concept with event mailing behavior by
  - adding a `send invitation` action
  - customizing email action of event with mass mailing
- https://github.com/acsone/acsone-addons/tree/8.0/event_multiple_registration
  # Event Multiple Registration
  
  The goal of this module is to register many partners to an event without
  duplication in one click.

I'm going to test it as they look interesting.

I apreciate you comments / opinions.

Thansk in advance
Regards,
Rafael

cc @pedrobaeza @antespi @carlosdauden @Tecnativa

**Comment by JonathanNEMRY** [comment]
cc @Olivier-LAURENT

**Comment by pedrobaeza** [comment]
https://github.com/OCA/event/blob/8.0/partner_event/wizard/res_partner_register_event.py already does the same of https://github.com/acsone/acsone-addons/tree/8.0/event_multiple_registration

**Comment by sbidoul** [comment]
@rafaelbn we are totally open to move any module in this repo to OCA if it is of general interest. Feel free to do the PRs with the usual git filter-branch dance to preserve history. We'll help in reviews.
