### ISSUE TITLE
[RFC] cagnotte* addons => OCA

### ISSUE THREAD

**Issue by rousseldenis** [acsone/acsone-addons#152]
We need to formalize from a functional point of view the usage of cagnotte addons in order to move them to OCA.

The idea is to create a new repository. Name proposal : account-pot as the nearest words are jackpot (which is more conoted) and pot. Source : https://www.linguee.com/french-english/translation/cagnotte.html.

Proposal of README : 

_This is based on the existing v10 version and target is v14_

## Prerequisites ##

* account_**pot**_base:

This module allows to define base modelisation for account pot management:

* A pot type with following data:
  * Type Name
  * An account
  * A sequence for pots
  * A product

![image](https://user-images.githubusercontent.com/19529533/117312410-4d8e8000-ae85-11eb-9dc5-99661df65105.png)

* A **pot** will contain:
  * The type
  * The **pot** balance
  * An active field
  * A company
  * A currency

![image](https://user-images.githubusercontent.com/19529533/117315460-035ace00-ae88-11eb-8d4b-2dd98425c62c.png)

## Flow ##

To provide input to **pot**, account entries should be created on the waiting account.

Those entries are mainly created through Customer Invoices.

![image](https://user-images.githubusercontent.com/19529533/117324489-20939a80-ae90-11eb-8e61-89adb299a2f2.png)

This has direct impact on **pot** balance:

![image](https://user-images.githubusercontent.com/19529533/117324662-4882fe00-ae90-11eb-8449-2abcf68db66f.png)

### Sale ###
_account_pot_sale_

The **pot** flow can be included in Sale flow in order to pay a Sale Order with reserve.

![image](https://user-images.githubusercontent.com/19529533/117628720-bf164900-b179-11eb-8b47-c6eca5da04d0.png)

After selecting the **pot**:

![image](https://user-images.githubusercontent.com/19529533/117628843-d9502700-b179-11eb-842b-de42518db95f.png)

The invoice generated will simply deduct that amount from the reserve account.

**Comment by rousseldenis** [comment]
repository README:

This repository contains modules in order to allow pot management through accounting entries. That approach is convenient in order to provide provisional entries (in a waiting account) that will be consumed later when payment is needed.

**Comment by rousseldenis** [comment]
@sbidoul @Cedric-Pigeon If you have input for this. @sbidoul Should I require repo creation on contributors ?

**Comment by rousseldenis** [comment]
After discussion, we can start on account-pot which seems reasonable.

**Comment by sbidoul** [comment]
TBH I'm not convinced with the name. How about opening a discussion in the contributors mailing list with an explanation of what the module(s) do(es) and asking help from native english speakers ?

**Comment by rousseldenis** [comment]
> TBH I'm not convinced with the name. How about opening a discussion in the contributors mailing list with an explanation of what the module(s) do(es) and asking help from native english speakers ?

I can do it for sure. Didn't want to imply community if it was too soon in our thinking.

**Comment by tarbib** [comment]
Hello @rousseldenis 
This looks really interesting!
I tried to install account_wallet_sale from Acsone's repo but I did not have a button to "pay with cagnotte" and I could not find the OCA repo.
Am I looking at the correct location?
Thanks
