### ISSUE TITLE
embedded picture: generalize filter

### ISSUE THREAD

**Issue by sbidoul** [acsone/acsone-addons#53]
Can it work for other images included through the frontend editor?

**Comment by lmignon** [comment]
yes it can and the widget should be removed or put in an other addons

**Comment by JonathanNEMRY** [comment]
By the way I just noticed that the `.js` is not properly referenced (still added with the old style) so the button to load the picture does not appears into the html widget.

But I don't think widget should be removed from anywhere else than from the module's name ..it should be placed into another addons that inherit of this one. And then properly inherit the `asset_backend` to include widget's modification.

**Comment by sbidoul** [comment]
Since there is already "widget" in the module name, I'd suggest moving the email filter to another module and make mail_html_widget_template depend on the new module?

**Comment by JonathanNEMRY** [comment]
:+1:
