### ISSUE TITLE
[html_widget_embedded_picture] Images are not diplayed in Thunderbird

### ISSUE THREAD

**Issue by cvinh** [acsone/acsone-addons#63]
In Thunderbird 31.3.0, embedded pictures are not displayed in email body (but they are in attachment).

At the first time, Thunderbird blocks images with the privacy option --> ... the images should be directly in the body (image1)

Then when the privacy option is off, the pictures do not display in the body but they are in attachment (image2)

In gmail, it's fine (image3)

![image1](https://cloud.githubusercontent.com/assets/7600872/7769437/53b0a0be-001f-11e5-912f-919360d55654.png)

![image2](https://cloud.githubusercontent.com/assets/7600872/7769439/5ae3a20a-001f-11e5-9e78-b03ce9ebb097.png)

![image3](https://cloud.githubusercontent.com/assets/7600872/7769443/64b6b420-001f-11e5-9c17-ed4bf765668f.png)

**Comment by lmignon** [comment]
@invitu thank you for the report. Is'it possible to have the html content of your mail?  We encountered some troubles in the past because Odoo has changed the way they format the url to reference an ir.attachment.

**Comment by cvinh** [comment]
hi laurent, (impossible to put some html stuff here...) I send you a private email...
cyril

**Comment by lmignon** [comment]
@invitu 
The problem come from the way we find the URLs in the document for the ir.attachement referenced in the document.
In your message URLs looks like

``` html
<img src="http://localhost:8069/website/image/ir.attachment/27_f345651/datas" style="display:block;border:none;min-height:50px" width="175">
<img src="http://localhost:8069/website/image/ir.attachment/28_aa2e3f0/datas" style="display:block;border:none;min-height:50px" width="175">
<img src="http://localhost:8069/website/image/ir.attachment/29_a265d8f/datas" style="display:block;border:none;min-height:50px" width="175">
```

In the code we expect that the part after 'ir.attachment' contains only figures since it should be the id of the attachement. (https://github.com/acsone/acsone-addons/blame/8.0/html_widget_embedded_picture/ir_mail_server.py#L49)

```
/ir.attachment/29_a265d8f/datas
```

In your case, the attachment also contains others chars. Therefore, the code is not able to find the attachment since `29_a265d8f` is not a valid Id.  The change in the way odoo build the id of the attachement in the url has been introduced by https://github.com/odoo/odoo/commit/bc5e6fa2cb577c11ae7236378b0175913d7d5648. 
We need to fix the code.

Regards,

lmi

**Comment by cvinh** [comment]
hello, thanks for analysing

i think odoo still takes the id of the attachment in the first part of the URL : 
/ir.attachment/29_a265d8f/datas --> 29 is the attachment id
so your code still fits the case because matching_buffer.keys() still are the attachment ids

I think the problem might be in the missing multipart/related which should be in the beginning of the mail

By the way, it should also be a thunderbird bug... https://bugzilla.mozilla.org/show_bug.cgi?id=61815

**Comment by cvinh** [comment]
dear laurent
I got it work with multipart/related in the email building : 
###
diff --git a/openerp/addons/base/ir/ir_mail_server.py b/openerp/addons/base/ir/ir_mail_server.py
@@ -303,7 +303,7 @@ class ir_mail_server(osv.osv):

```
     email_body_utf8 = ustr(body).encode('utf-8')
     email_text_part = MIMEText(email_body_utf8, _subtype=subtype, _charset='utf-8')
```
-        msg = MIMEMultipart()
- ```
     msg = MIMEMultipart(_subtype='related',)
  
   if not message_id:
  ```
  
  ###
  I guess this is related to the difficulty to have embedded images with "cid" working in most of the email clients...

Is there a way to include that in your module ?

**Comment by lmignon** [comment]
@invitu thank you for your work. I'm on vacation and I'll be back at work next monday.

**Comment by cvinh** [comment]
hello jonathan, it works with your branch 8.0-fix_63_mail_related_multipart-jne

**Comment by ysantiago** [comment]
Hello @invitu @lmignon 

Can you please give me orientation about how can I do to obtain the image attachment id `27_f345651`, to do the following:

`<img src="http://localhost:8069/website/image/ir.attachment/27_f345651/datas">`

Thanks a lot

**Comment by flotho** [comment]
Hi @ysantiago , personnaly I succeed in making it work and readable in my webmail by using the ckeditor widget and choosing my full URL with attachment URL copy pasted from the drop down attachment menu.
