### ISSUE TITLE
Porting readonly_bypass on v7

### ISSUE THREAD

**Issue by petrus-v** [acsone/acsone-addons#69]
Hi!

readonly_bypass description looks fit my needs!

I would like to port this module on v7 if it's not already done. How would you like I do it? directly create a PR in OCA/web or OCA/server tools repo with ascone as author ? or directly a PR in this repo?

regards

**Comment by JonathanNEMRY** [comment]
Hello @petrus-v 
`readonly_bypass` is currently not ported into v7 but of course you're welcome for a PR into `acsone-addons/7.0`. Once this PR will be merge and as it this module seems to have some interest then we could propose it to the OCA/web repository 7.0/8.0
Don't hesitate if you have any question!
-jne

**Comment by sbidoul** [comment]
@petrus-v great you are interested in this!

Let's move it to OCA first. I'm doing a PR to OCA so you can review it and cherry-pick the commits to create the 7.0 branch.

I suppose OCA/web is the best repo for this?

**Comment by lmignon** [comment]
@sbidoul IMO OCA/web is the right place.

**Comment by petrus-v** [comment]
All right,

Let me know when you've done the PR, I'll review it.

Thank you very much.

**Comment by sbidoul** [comment]
@petrus-v here is the PR: https://github.com/OCA/web/pull/162

If you see things that can be improved, do not hesitate to PR's against that branch.

**Comment by petrus-v** [comment]
Great!

I gonna review it.

Thanks again
