### ISSUE TITLE
[html_widget_embedded_picture] accented characters are not well displayed

### ISSUE THREAD

**Issue by cvinh** [acsone/acsone-addons#71]
Hello

With mass mailing which contents accented characters, those characters are not decoded well

Solution is to add 'decode('utf-8') to the get_payload function :

diff --git a/html_widget_embedded_picture/ir_mail_server.py b/html_widget_embedded_picture/ir_mail_server.py
index f3d6d9a..25b1092 100644
--- a/html_widget_embedded_picture/ir_mail_server.py
+++ b/html_widget_embedded_picture/ir_mail_server.py
@@ -38,7 +38,7 @@ class ir_mail_server(orm.Model):
     _inherit = "ir.mail_server"

```
 def embedd_ir_attachment(self, cr, uid, message, body_part, context=None):
```
-        html_str = body_part.get_payload(decode=True)
-        html_str = body_part.get_payload(decode=True).decode('utf-8')
       root = html.document_fromstring(html_str)
       matching_buffer = {}
       for child in root.iter():

**Comment by flotho** [comment]
:+1:

**Comment by lmignon** [comment]
@invitu   @flotho  see https://github.com/acsone/acsone-addons/pull/62

**Comment by sbidoul** [comment]
@invitu @flotho #62 is merged. Does it solve the issue for you?
